version: '3'

services:

  mongo:
    image: "mongo:4.2"
    volumes:
      - './data/mongo:/data/db'
  redis:
    image: "redis:7.0"
    volumes:
      - './data/redis:/var/lib/redis'
      - './data/redis.conf:/usr/local/etc/redis/redis.conf'

  clickhouse:
# for M1 macs
#    image: "lunalabsltd/clickhouse-server:21.7.2.7-arm"
    image: "yandex/clickhouse-server:latest"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Need just for reverse traffic for demo.squzy.app
  proxy_http:
      image: "jwilder/nginx-proxy:latest"

  squzy_storage:
    image: "squzy/squzy_storage:v1.12.2"
    restart: on-failure
    depends_on:
      - clickhouse
    environment:
      - INCIDENT_SERVER_HOST=squzy_incident_management:9097
      - ENABLE_INCIDENT=true
      - DB_HOST=clickhouse
      - DB_NAME=default
      - DB_USER=default
      - DB_PASSWORD=
      - DB_PORT=9000
      - LOG_LEVEL=info
      - PORT=9092

  squzy_monitoring:
    image: "squzy/squzy_monitoring:v1.12.2"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
      - redis
    environment:
      - PORT=9090
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092

  squzy_agent_server:
    image: "squzy/squzy_agent_server:v1.12.2"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
    environment:
      - PORT=9091
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092
    ports:
      - "9091:9091"

  squzy_api:
    image: "squzy/squzy_api:v1.12.2"
    restart: on-failure
    depends_on:
      - squzy_agent_server
      - squzy_monitoring
      - squzy_storage
      - squzy_application_monitoring
      - squzy_notification_management
      - squzy_incident_management
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - INCIDENT_SERVER_HOST=squzy_incident_management:9097
      - MONITORING_SERVER_HOST=squzy_monitoring:9090
      - AGENT_SERVER_HOST=squzy_agent_server:9091
      - STORAGE_SERVER_HOST=squzy_storage:9092
      - APPLICATION_MONITORING_SERVER_HOST=squzy_application_monitoring:9095
      - NOTIFICATION_SERVER_HOST=squzy_notification_management:9098
    ports:
      - "8082:8080"

  squzy_dashboard:
    image: "squzy/squzy_dashboard:v1.11.6"
    restart: on-failure
    depends_on:
      - squzy_api
    environment:
      - API_HOST=squzy_api:8080
    ports:
      - "8081:80"

  squzy_application_monitoring:
    image: "squzy/squzy_application_monitoring:v1.12.2"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
    environment:
      - PORT=9095
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092

  squzy_incident_management:
    image: "squzy/squzy_incident:v1.12.2"
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
      - LOG_LEVEL=info
      - STORAGE_HOST=squzy_storage:9092
      - NOTIFICATION_HOST=squzy_notification_management:9098

  squzy_notification_management:
    image: "squzy/squzy_notification:v1.12.2"
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongo
      - STORAGE_HOST=squzy_storage:9092
      - DASHBOARD_HOST=https://demo.squzy.app
      - PORT=9098

  squzy_web:
    image: "squzy/squzy_web:v1.11.1"
    restart: on-failure
    ports:
      - "8080:80"
