version: '3'

services:

  mongo:
    image: "mongo:latest"
    volumes:
      - './data:/data/db'

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  squzy_storage:
    image: "squzy/squzy_storage:v1.9.0"
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - INCIDENT_SERVER_HOST=squzy_incident_management:9097
      - ENABLE_INCIDENT=true
      - DB_HOST=postgres
      - DB_NAME=database
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=9092

  squzy_monitoring:
    image: "squzy/squzy_monitoring:v1.9.0"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
    environment:
      - PORT=9090
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092

  squzy_agent_server:
    image: "squzy/squzy_agent_server:v1.9.0"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
    environment:
      - PORT=9091
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092
    ports:
      - "9091:9091"

  squzy_api:
    image: "squzy/squzy_api:v1.9.0"
    restart: on-failure
    depends_on:
      - squzy_agent_server
      - squzy_monitoring
      - squzy_storage
      - squzy_application_monitoring
    environment:
      - PORT=8080
      - INCIDENT_SERVER_HOST=squzy_incident_management:9097
      - MONITORING_SERVER_HOST=squzy_monitoring:9090
      - AGENT_SERVER_HOST=squzy_agent_server:9091
      - STORAGE_SERVER_HOST=squzy_storage:9092
      - APPLICATION_MONITORING_SERVER_HOST=squzy_application_monitoring:9095
    ports:
      - "8082:8080"

  squzy_dashboard:
    image: "squzy/squzy_dashboard:v1.9.1"
    restart: on-failure
    depends_on:
      - squzy_api
    environment:
      - API_HOST=squzy_api:8080
    ports:
      - "8081:80"

  squzy_application_monitoring:
    image: "squzy/squzy_application_monitoring:v1.9.0"
    restart: on-failure
    depends_on:
      - mongo
      - squzy_storage
    environment:
      - PORT=9095
      - MONGO_URI=mongodb://mongo
      - SQUZY_STORAGE_HOST=squzy_storage:9092

  squzy_incident_management:
    image: "squzy/squzy_incident:v1.9.0"
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
      - STORAGE_HOST=squzy_storage:9092

  squzy_web:
    image: "squzy/squzy_web:v1.9.0"
    restart: on-failure
    ports:
      - "8080:80"
